name: Run notebook

on:
  schedule:
    - cron: '0 8 * * *' # Runs every day at 8:00 AM UTC

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace ADS507-Team7.ipynb
          
      - name: Commit changes
        run: |
          git config --global user.email "trevsauer@gmail.com"
          git config --global user.name "trevsauer"
          git add ADS507-Team7.ipynb
          git commit -m "Update notebook output"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main